[package]
name = "classify"
version = "0.1.0"
authors = ["WasmEdge"]
edition = "2018"

[[bin]]
name = "classify"
path = "src/main.rs"

[dependencies]
wasmedge_tensorflow_interface = "^0.2.0"
wasm-bindgen = "=0.2.61"
